### PR TITLE
hotfix/search functionality restored + other small fixes

### LINKED ISSUE #34: Revamp Search Bar for List of Obj. Func.
Search bar currently exists for Blog page, and it exists visually for the rest of the website but has no functionality elsewhere.
Add functionality for remaining pages.

### PR DESCRIPTION
**Pull request by nathanjslim**

### CODE REVIEW

File: client/src/pages/Blog.jsx [hunk 1]
```diff
@@ -1,67 +1,56 @@
...
+    useEffect(() => {
+        fetchBlogData();
+    }, []);
+
+    // useEffect(() => {
+    //     setFilteredPosts(posts.filter(post => post.title.toLowerCase().includes(searchText) || post.content.toLowerCase().includes(searchText)));
+    // }, [searchText, posts]);
+
+    const fetchBlogData = async () => {
+        const response = await fetch('http://localhost:8000/api/posts');
```
Comment (StephenODea54) [inline client/src/pages/Blog.jsx]: Mind changing this so we are all using `axios`? (Not that `axios` is much better than the built in `fetch` methods, but just for consistency (we are using axios for the blogs and tags atm.

Code would be:

```javascript
axios.get("http://localhost:8000/api/posts")
  .then(response => setBlogPosts(response.data)
  .catch(error => console.log(error)) // Optional
```

**Review by StephenODea54 — APPROVED** [review]
This is good to merge even disregarding my comment.

**Review by jpatterson933 — APPROVED** [review]
